import type { Metadata } from "next";
import "./globals.css";
import VisualEditsMessenger from "../visual-edits/VisualEditsMessenger";
import Script from "next/script";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        {/* Boot theme before paint (Material You accent + dark mode) */}
        <Script id="boot-theme" strategy="beforeInteractive">{`
          try {
            const key = 'theme_settings_v1';
            const saved = localStorage.getItem(key);
            const defaults = { accent: '#7c3aed', dark: false };
            const cfg = saved ? { ...defaults, ...JSON.parse(saved) } : defaults;
            const root = document.documentElement;
            root.style.setProperty('--sidebar-primary', cfg.accent);
            root.style.setProperty('--primary', cfg.accent);
            root.style.setProperty('--chart-1', cfg.accent);
            if (cfg.dark) root.classList.add('dark'); else root.classList.remove('dark');
          } catch (e) { /* no-op */ }
        `}</Script>
        <Script
          src="https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/scripts//route-messenger.js"
          strategy="afterInteractive"
          data-target-origin="*"
          data-message-type="ROUTE_CHANGE"
          data-include-search-params="true"
          data-only-in-iframe="true"
          data-debug="true"
          data-custom-data='{"appName": "YourApp", "version": "1.0.0", "greeting": "hi"}'
        />
        {children}
        <VisualEditsMessenger />
      </body>
    </html>
  );
}